# Generated by Django 6.0.3 on 2026-03-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
