# Generated by Django 6.0.3 on 2026-03-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
