# Generated by Django 6.0.3 on 2026-04-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_mobileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='名字')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
