# Generated by Django 6.0.3 on 2026-05-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=32, verbose_name='年龄')),
                ('img', models.FileField(max_length=128, upload_to='', verbose_name='文件')),
            ],
        ),
    ]
