# Generated by Django 6.0.3 on 2026-05-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('count', models.IntegerField(max_length=32, verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='', verbose_name='Logo')),
            ],
        ),
    ]
